// lib/sentences.ts (Specialized for USER 1)
export const SENTENCE_BANK = [
  // Group 1: The 'I' and 'T' Foundation
  "I think it is time to tell the truth.",
  "To be honest, I truly don't know that.",
  "I told them that Tuesday is fine.",
  "The little kitten bit the thick string.",
  "I tried to tie the knot, but it slipped.",
  "This is the third time I thought about it.",
  "I invited him, but Tommy didn't attend.",
  "Today is the best day to try it out.",
  "It is important to treat people well.",
  "I totally forgot to take out the trash.",

  // Group 2: Conversational Punctuation
  '"Wait," she said, "I think it\'s broken!"',
  "He couldn't believe it; it was huge.",
  "I'll be there soon - don't start without me.",
  '"Is this the right way?" asked the driver.',
  "You've got to be kidding me, right?",
  "We're going to need a bigger boat.",
  "They're not here yet, but they will be.",
  '"Stop right there!" the officer shouted.',
  "It's raining, so we'll stay inside today.",
  "Haven't you seen this movie before?",

  // Group 3: The 't' and 'i' Heavyweights
  "Title your paper and list the details.",
  "Initial testing is still in transition.",
  "Little institutions sit in the city.",
  "The initiative takes time to institute.",
  "It is fitting that the timing is tight.",
  "I still think it is a little bit toxic.",
  "Tillie is knitting a tiny little mitten.",
  "The titanic ship hit the bitter ice.",
  "I sit silently in the little tent.",
  "It takes intuition to hit the target.",

  // Group 4: High-Exit & Double Letters
  "The small wooden boat bobbed over the waves.",
  "We need a good broom to sweep the floor.",
  "She took a look at the smooth velvet book.",
  "Bees buzz over the sweet summer blossoms.",
  "Seven brave wolves moved above the valley.",
  "The balloon floated smoothly over the hill.",
  "He stood over the oven cooking food.",
  "We will see the woodchuck borrow a root.",
  "A cool breeze blows over the deep water.",
  "I feel good about the progress we made.",

  // Group 5: Contextual Digits & Capital Spread
  "Call me at 5 or 6 in the morning.",
  "My flight is at 8:30, not 9:15!",
  "He bought 4 apples and 2 bananas.",
  "The code is 703, but try 1982 also.",
  "At exactly 12:45, the bell will ring.",
  "Alice and Bob left for Canada on May 10.",
  "Queen Victoria ruled for 63 years.",
  "X-rays show 4 broken bones in his foot.",
  "Zelda played jazz for 7 hours straight.",
  "Just 1 quick fox leaped over 2 lazy dogs.",

  // Group 6: Capital Letter Completion (A-Z Coverage)
  "All good boys deserve fine things.",
  "Please bring Charlie to the party!",
  "Dogs and cats make great pets.",
  "Everyone felt happy in the garden.",
  "George hoped that Kelly would jump.",
  "Louis made a nice omelet for us.",
  "Quiet rivers silently wind through.",
  "Umbrellas keep the heavy rain out.",
  "Very wild zebras exist in Africa.",
  "Yellow xylophones play quiet tunes.",

  // Group 7: Advanced Apostrophes & Contractions
  "We've been here for hours, haven't we?",
  "It's a shame they're not coming.",
  "You'll need to know who's in charge.",
  "I'd love to, but I've got to work.",
  "She's the one who didn't understand.",
  "Let's see if shouldn't is a word.",
  "Won't you please tell me what's wrong?",
  "They'll find out that we're right.",
  "I'm sure that doesn't matter now.",
  "He'll come if you've asked him nicely.",

  // Group 8: The \"-ing\" and \"-tion\" Rhythm Section
  "Running and jumping are tiring things.",
  "Information is flowing from the station.",
  "Thinking about nothing is relaxing.",
  "The operation requires full attention.",
  "Bring the ring to the wedding morning.",
  "Action and reaction happen together.",
  "Singing songs is a fun tradition.",
  "Finding the missing pieces is thrilling.",
  "Creation of the nation took time.",
  "Making a painting requires imagination.",

  // Group 9: Digits, Dates, & Dashes
  "Room 101 is down the hall.",
  "Her birthday is October 14, 1998.",
  "Dial 9-1-1 in a real emergency.",
  "Flight 205 leaves at 3:30 today.",
  "He won 1st place in the 5k run!",
  "Read pages 45-60 for tomorrow.",
  "The year 2026 is going fast.",
  "About 8 or 9 people are here.",
  "I bought 3 shirts and 1 hat.",
  "Call me back at 555-0198.",

  // Group 10: The Ultimate 't' & 'i' Gauntlet (The Boss Fight)
  "It is critical to hit the target.",
  "Tim is sitting in the little attic.",
  "I think knitting is a bit tiring.",
  "This limits the initial utility.",
  "It takes time to paint it right.",
  "I will split it into little bits.",
  "A stitch in time saves nine!",
  "The tight string is totally split.",
  "I still insist that it is fitting.",
  "It is finished, I think it is time.",
];
